version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"